routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Middleware\CheckRole;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//facebook login
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');
//dd();
Route::middleware(['auth'])->group( function () {
    Route::get('users/{id}', 'UserController@show');
    Route::resource('jobs', 'JobController');
    Route::resource('jobUserCoders', 'JobUserCoderController');
    Route::resource('jobUserHirers', 'JobUserHirerController');
    Route::get('users/{id}/edit', 'UserController@edit');
    Route::put('users/{id}', 'UserController@update');
    Route::patch('users/{id}', 'UserController@update');
});
Route::middleware(['checkRole'])->group( function () {
    //only admin can access this route
    Route::resource('users', 'UserController');
    Route::resource('categories', 'CategoryController');
    Route::resource('roles', 'RoleController');
    Route::resource('settings', 'SettingController');
});

app/Models/JobUserHirer.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class JobUserHirer
 * @package App\Models
 * @version May 24, 2019, 11:04 pm UTC
 *
 * @property integer user_id
 * @property integer job_id
 * @property integer category_id
 */
class JobUserHirer extends Model
{
    use SoftDeletes;

    public $table = 'job_user_hirer';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'user_id',
        'job_id',
        'category_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'job_id' => 'integer',
        'category_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'user_id' => 'required',
        'job_id' => 'required',
        'category_id' => 'required'
    ];

    
}

app/Http/Controllers/JobUserHirerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateJobUserHirerRequest;
use App\Http\Requests\UpdateJobUserHirerRequest;
use App\Repositories\JobUserHirerRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class JobUserHirerController extends AppBaseController
{
    /** @var  JobUserHirerRepository */
    private $jobUserHirerRepository;

    public function __construct(JobUserHirerRepository $jobUserHirerRepo)
    {
        $this->jobUserHirerRepository = $jobUserHirerRepo;
    }

    /**
     * Display a listing of the JobUserHirer.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->jobUserHirerRepository->pushCriteria(new RequestCriteria($request));
        $jobUserHirers = $this->jobUserHirerRepository->all();

        return view('job_user_hirers.index')
            ->with('jobUserHirers', $jobUserHirers);
    }

    /**
     * Show the form for creating a new JobUserHirer.
     *
     * @return Response
     */
    public function create()
    {
        return view('job_user_hirers.create');
    }

    /**
     * Store a newly created JobUserHirer in storage.
     *
     * @param CreateJobUserHirerRequest $request
     *
     * @return Response
     */
    public function store(CreateJobUserHirerRequest $request)
    {
        $input = $request->all();

        $jobUserHirer = $this->jobUserHirerRepository->create($input);

        Flash::success('Job User Hirer saved successfully.');

        return redirect(route('jobUserHirers.index'));
    }

    /**
     * Display the specified JobUserHirer.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $jobUserHirer = $this->jobUserHirerRepository->findWithoutFail($id);

        if (empty($jobUserHirer)) {
            Flash::error('Job User Hirer not found');

            return redirect(route('jobUserHirers.index'));
        }

        return view('job_user_hirers.show')->with('jobUserHirer', $jobUserHirer);
    }

    /**
     * Show the form for editing the specified JobUserHirer.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $jobUserHirer = $this->jobUserHirerRepository->findWithoutFail($id);

        if (empty($jobUserHirer)) {
            Flash::error('Job User Hirer not found');

            return redirect(route('jobUserHirers.index'));
        }

        return view('job_user_hirers.edit')->with('jobUserHirer', $jobUserHirer);
    }

    /**
     * Update the specified JobUserHirer in storage.
     *
     * @param  int              $id
     * @param UpdateJobUserHirerRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateJobUserHirerRequest $request)
    {
        $jobUserHirer = $this->jobUserHirerRepository->findWithoutFail($id);

        if (empty($jobUserHirer)) {
            Flash::error('Job User Hirer not found');

            return redirect(route('jobUserHirers.index'));
        }

        $jobUserHirer = $this->jobUserHirerRepository->update($request->all(), $id);

        Flash::success('Job User Hirer updated successfully.');

        return redirect(route('jobUserHirers.index'));
    }

    /**
     * Remove the specified JobUserHirer from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $jobUserHirer = $this->jobUserHirerRepository->findWithoutFail($id);

        if (empty($jobUserHirer)) {
            Flash::error('Job User Hirer not found');

            return redirect(route('jobUserHirers.index'));
        }

        $this->jobUserHirerRepository->delete($id);

        Flash::success('Job User Hirer deleted successfully.');

        return redirect(route('jobUserHirers.index'));
    }
}

resources/views/job_user_hirers/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Job User Hirer
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'jobUserHirers.store']) !!}

                        @include('job_user_hirers.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/job_user_hirers/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Job User Hirer
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($jobUserHirer, ['route' => ['jobUserHirers.update', $jobUserHirer->id], 'method' => 'patch']) !!}

                        @include('job_user_hirers.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/job_user_hirers/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Job Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('job_id', 'Job Id:') !!}
    {!! Form::number('job_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Category Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('category_id', 'Category Id:') !!}
    {!! Form::number('category_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('jobUserHirers.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/job_user_hirers/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Job User Hirers</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('jobUserHirers.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('job_user_hirers.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/job_user_hirers/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Job User Hirer
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('job_user_hirers.show_fields')
                    <a href="{!! route('jobUserHirers.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/job_user_hirers/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $jobUserHirer->id !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{!! $jobUserHirer->user_id !!}</p>
</div>

<!-- Job Id Field -->
<div class="form-group">
    {!! Form::label('job_id', 'Job Id:') !!}
    <p>{!! $jobUserHirer->job_id !!}</p>
</div>

<!-- Category Id Field -->
<div class="form-group">
    {!! Form::label('category_id', 'Category Id:') !!}
    <p>{!! $jobUserHirer->category_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $jobUserHirer->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $jobUserHirer->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $jobUserHirer->deleted_at !!}</p>
</div>

resources/views/job_user_hirers/table.blade.php
<div class="table-responsive">
    <table class="table" id="jobUserHirers-table">
        <thead>
            <tr>
                <th>User Id</th>
        <th>Job Id</th>
        <th>Category Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($jobUserHirers as $jobUserHirer)
            <tr>
                <td>{!! $jobUserHirer->user_id !!}</td>
            <td>{!! $jobUserHirer->job_id !!}</td>
            <td>{!! $jobUserHirer->category_id !!}</td>
                <td>
                    {!! Form::open(['route' => ['jobUserHirers.destroy', $jobUserHirer->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('jobUserHirers.show', [$jobUserHirer->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('jobUserHirers.edit', [$jobUserHirer->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>