routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Middleware\CheckRole;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//facebook login
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');
//dd();
Route::middleware(['auth'])->group( function () {
    Route::get('users/{id}', 'UserController@show');
    Route::resource('jobs', 'JobController');
    Route::resource('jobUserCoders', 'JobUserCoderController');
    Route::resource('jobUserHirers', 'JobUserHirerController');
    Route::get('users/{id}/edit', 'UserController@edit');
    Route::put('users/{id}', 'UserController@update');
    Route::patch('users/{id}', 'UserController@update');
});
Route::middleware(['checkRole'])->group( function () {
    //only admin can access this route
    Route::resource('users', 'UserController');
    Route::resource('categories', 'CategoryController');
    Route::resource('roles', 'RoleController');
    Route::resource('settings', 'SettingController');
});

app/Models/JobUserCoder.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class JobUserCoder
 * @package App\Models
 * @version May 24, 2019, 11:04 pm UTC
 *
 * @property integer user_id
 * @property integer job_id
 * @property integer category_id
 */
class JobUserCoder extends Model
{
    use SoftDeletes;

    public $table = 'job_user_coder';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'user_id',
        'job_id',
        'category_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'job_id' => 'integer',
        'category_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'user_id' => 'required',
        'job_id' => 'required',
        'category_id' => 'required'
    ];

    
}

app/Http/Controllers/JobUserCoderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateJobUserCoderRequest;
use App\Http\Requests\UpdateJobUserCoderRequest;
use App\Repositories\JobUserCoderRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class JobUserCoderController extends AppBaseController
{
    /** @var  JobUserCoderRepository */
    private $jobUserCoderRepository;

    public function __construct(JobUserCoderRepository $jobUserCoderRepo)
    {
        $this->jobUserCoderRepository = $jobUserCoderRepo;
    }

    /**
     * Display a listing of the JobUserCoder.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->jobUserCoderRepository->pushCriteria(new RequestCriteria($request));
        $jobUserCoders = $this->jobUserCoderRepository->all();

        return view('job_user_coders.index')
            ->with('jobUserCoders', $jobUserCoders);
    }

    /**
     * Show the form for creating a new JobUserCoder.
     *
     * @return Response
     */
    public function create()
    {
        return view('job_user_coders.create');
    }

    /**
     * Store a newly created JobUserCoder in storage.
     *
     * @param CreateJobUserCoderRequest $request
     *
     * @return Response
     */
    public function store(CreateJobUserCoderRequest $request)
    {
        $input = $request->all();

        $jobUserCoder = $this->jobUserCoderRepository->create($input);

        Flash::success('Job User Coder saved successfully.');

        return redirect(route('jobUserCoders.index'));
    }

    /**
     * Display the specified JobUserCoder.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $jobUserCoder = $this->jobUserCoderRepository->findWithoutFail($id);

        if (empty($jobUserCoder)) {
            Flash::error('Job User Coder not found');

            return redirect(route('jobUserCoders.index'));
        }

        return view('job_user_coders.show')->with('jobUserCoder', $jobUserCoder);
    }

    /**
     * Show the form for editing the specified JobUserCoder.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $jobUserCoder = $this->jobUserCoderRepository->findWithoutFail($id);

        if (empty($jobUserCoder)) {
            Flash::error('Job User Coder not found');

            return redirect(route('jobUserCoders.index'));
        }

        return view('job_user_coders.edit')->with('jobUserCoder', $jobUserCoder);
    }

    /**
     * Update the specified JobUserCoder in storage.
     *
     * @param  int              $id
     * @param UpdateJobUserCoderRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateJobUserCoderRequest $request)
    {
        $jobUserCoder = $this->jobUserCoderRepository->findWithoutFail($id);

        if (empty($jobUserCoder)) {
            Flash::error('Job User Coder not found');

            return redirect(route('jobUserCoders.index'));
        }

        $jobUserCoder = $this->jobUserCoderRepository->update($request->all(), $id);

        Flash::success('Job User Coder updated successfully.');

        return redirect(route('jobUserCoders.index'));
    }

    /**
     * Remove the specified JobUserCoder from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $jobUserCoder = $this->jobUserCoderRepository->findWithoutFail($id);

        if (empty($jobUserCoder)) {
            Flash::error('Job User Coder not found');

            return redirect(route('jobUserCoders.index'));
        }

        $this->jobUserCoderRepository->delete($id);

        Flash::success('Job User Coder deleted successfully.');

        return redirect(route('jobUserCoders.index'));
    }
}

resources/views/job_user_coders/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Job User Coder
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'jobUserCoders.store']) !!}

                        @include('job_user_coders.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/job_user_coders/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Job User Coder
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($jobUserCoder, ['route' => ['jobUserCoders.update', $jobUserCoder->id], 'method' => 'patch']) !!}

                        @include('job_user_coders.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/job_user_coders/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Job Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('job_id', 'Job Id:') !!}
    {!! Form::number('job_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Category Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('category_id', 'Category Id:') !!}
    {!! Form::number('category_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('jobUserCoders.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/job_user_coders/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Job User Coders</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('jobUserCoders.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('job_user_coders.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/job_user_coders/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Job User Coder
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('job_user_coders.show_fields')
                    <a href="{!! route('jobUserCoders.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/job_user_coders/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $jobUserCoder->id !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{!! $jobUserCoder->user_id !!}</p>
</div>

<!-- Job Id Field -->
<div class="form-group">
    {!! Form::label('job_id', 'Job Id:') !!}
    <p>{!! $jobUserCoder->job_id !!}</p>
</div>

<!-- Category Id Field -->
<div class="form-group">
    {!! Form::label('category_id', 'Category Id:') !!}
    <p>{!! $jobUserCoder->category_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $jobUserCoder->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $jobUserCoder->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $jobUserCoder->deleted_at !!}</p>
</div>

resources/views/job_user_coders/table.blade.php
<div class="table-responsive">
    <table class="table" id="jobUserCoders-table">
        <thead>
            <tr>
                <th>User Id</th>
        <th>Job Id</th>
        <th>Category Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($jobUserCoders as $jobUserCoder)
            <tr>
                <td>{!! $jobUserCoder->user_id !!}</td>
            <td>{!! $jobUserCoder->job_id !!}</td>
            <td>{!! $jobUserCoder->category_id !!}</td>
                <td>
                    {!! Form::open(['route' => ['jobUserCoders.destroy', $jobUserCoder->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('jobUserCoders.show', [$jobUserCoder->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('jobUserCoders.edit', [$jobUserCoder->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>